name: Build Storybook

on:
    workflow_dispatch:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    release:
        types: [published]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-root
    cancel-in-progress: true

jobs:
    pre-job:
        runs-on: ubuntu-latest
        outputs:
            should_run_server: ${{ steps.found_paths.outputs.server == 'true' || steps.should_force.outputs.should_force == 'true' }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - id: found_paths
              uses: dorny/paths-filter@v3
              with:
                  filters: |
                      server:
                        - 'apps/wizarr-frontend/src/**/*.{mdx,stories.ts,stories.tsx,stories.js,stories.jsx,vue}'

            - name: Check if we should force jobs to run
              id: should_force
              run: echo "should_force=${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}" >> "$GITHUB_OUTPUT"

        build-storybook:
            name: Build Storybook
            needs: pre-job
            if: ${{ needs.pre-job.outputs.should_run_server == 'false' && !github.event.pull_request.head.repo.fork }}
            runs-on: ubuntu-latest
            steps:
                - name: Generate a token
                  id: generate-token
                  uses: actions/create-github-app-token@v1
                  with:
                      app-id: ${{ secrets.PUSH_O_MATIC_APP_ID }}
                      private-key: ${{ secrets.PUSH_O_MATIC_APP_KEY }}

                - name: Checkout Repository
                  uses: actions/checkout@v2
                  with:
                      fetch-depth: 0

                - name: Set up Node.js
                  uses: actions/setup-node@v4
                  with:
                      node-version: 22.11.0

                - name: Install Dependencies
                  run: npm ci --ignore-scripts

                - name: Build Storybook
                  run: npx nx run wizarr-frontend:build-storybook

                - name: Deploy Storybook
                  uses: peaceiris/actions-gh-pages@v3
                  with:
                      external_repository: wizarrrrr/storybook.wizarr.org
                      personal_token: ${{ steps.generate-token.outputs.token }}
                      publish_dir: ./dist/storybook/wizarr-frontend
                      cname: storybook.wizarr.org

                - name: Deploy Storybook to Chromatic
                  run: npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --exit-zero-on-changes --storybook-build-dir ./dist/storybook/wizarr-frontend
                  env:
                      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
