name: Docker Builds

on:
    workflow_run:
        workflows: ["Prepare new release"]
        types:
            - completed
    repository_dispatch:
        types: [trigger-docker-builds]

jobs:
    extract-version:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.version.outputs.version }}
        steps:
            - name: Extract version from repository dispatch
              if: github.event_name == 'repository_dispatch'
              id: version
              run: |
                  echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT

            - name: Extract version from release
              if: github.event_name == 'workflow_run'
              id: version
              run: |
                  # Get the release tag from the triggering workflow
                  TAG=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/repos/${{ github.repository }}/releases/latest" | \
                    jq -r '.tag_name')
                  # Remove 'v' prefix if present
                  VERSION=${TAG#v}
                  echo "version=${VERSION}" >> $GITHUB_OUTPUT

    build-frontend:
        needs: extract-version
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push frontend image
              working-directory: apps/wizarr-frontend
              run: |
                  docker build -t ghcr.io/${{ github.repository_owner }}/wizarr-frontend:latest .
                  docker push ghcr.io/${{ github.repository_owner }}/wizarr-frontend:latest

                  docker tag ghcr.io/${{ github.repository_owner }}/wizarr-frontend:latest ghcr.io/${{ github.repository_owner }}/wizarr-frontend:${{ needs.extract-version.outputs.version }}
                  docker push ghcr.io/${{ github.repository_owner }}/wizarr-frontend:${{ needs.extract-version.outputs.version }}

    build-backend:
        needs: extract-version
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push backend image
              working-directory: apps/wizarr-backend
              run: |
                  docker build -t ghcr.io/${{ github.repository_owner }}/wizarr-backend:latest .
                  docker push ghcr.io/${{ github.repository_owner }}/wizarr-backend:latest

                  docker tag ghcr.io/${{ github.repository_owner }}/wizarr-backend:latest ghcr.io/${{ github.repository_owner }}/wizarr-backend:${{ needs.extract-version.outputs.version }}
                  docker push ghcr.io/${{ github.repository_owner }}/wizarr-backend:${{ needs.extract-version.outputs.version }}
