name: Docker Builds

on:
    workflow_run:
        workflows: ["Prepare new release"]
        types:
            - completed
    repository_dispatch:
        types: [trigger-docker-builds]

jobs:
    extract-version:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.get-version.outputs.version }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Get version from package.json
              id: get-version
              run: |
                  VERSION=$(jq -r '.version' package.json)
                  echo "version=${VERSION}" >> $GITHUB_OUTPUT
                  echo "Extracted version: ${VERSION}"

    build-frontend:
        needs: extract-version
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push frontend image
              working-directory: apps/wizarr-frontend
              run: |
                  docker build -t ghcr.io/${{ github.repository_owner }}/wizarr-frontend:latest .
                  docker push ghcr.io/${{ github.repository_owner }}/wizarr-frontend:latest

                  docker tag ghcr.io/${{ github.repository_owner }}/wizarr-frontend:latest ghcr.io/${{ github.repository_owner }}/wizarr-frontend:${{ needs.extract-version.outputs.version }}
                  docker push ghcr.io/${{ github.repository_owner }}/wizarr-frontend:${{ needs.extract-version.outputs.version }}

    build-backend:
        needs: extract-version
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push backend image
              working-directory: apps/wizarr-backend
              run: |
                  docker build -t ghcr.io/${{ github.repository_owner }}/wizarr-backend:latest .
                  docker push ghcr.io/${{ github.repository_owner }}/wizarr-backend:latest

                  docker tag ghcr.io/${{ github.repository_owner }}/wizarr-backend:latest ghcr.io/${{ github.repository_owner }}/wizarr-backend:${{ needs.extract-version.outputs.version }}
                  docker push ghcr.io/${{ github.repository_owner }}/wizarr-backend:${{ needs.extract-version.outputs.version }}
